#!/bin/bash

# Create a virtual network using network namespaces and veth pairs
# to connect them.
# Assuming $CONFIGDIR == "cfg":
# * Files in cfg/<Node name> will be overlaid over /etc, i.e. if a file with
# the same name exists in both directory, the one in cfg/<Node name> will
# be the one used.
# * If cfg/<Node name>_$BOOT (defaults to cfg/<Node name>_boot) exists and
# is executable, it will be executed when the node is created
# * If cfg/<Node name>_$STARTUP (defaults to cfg/<Node name>_start) exists and
# is executable, it will be executed when the whole network has started
#

# IMPORTANT NOTE: Node names MUST NOT exceed 9 characters.
# This is due to the limitation to 14 characters of interface names

# You can override any of these settings on a per-topology basis
# Group number
GROUPNUMBER=3
# Node configs
CONFIGDIR=group3_cfg
# boot script name
BOOT="boot.sh"
# startup script name
STARTUP="start.sh"
PREFIXLEN_as200=48
PREFIXBASE_as200="fd00:200:${GROUPNUMBER}::/${PREFIXLEN_as200}"
# You can reuse the above two to generate ip addresses/routes, ...
# in you boot and startup scripts
# e.g. "${PREFIXBASE}:1234::/$((PREFIXLEN+16))"

# This function describes the network topology that we want to emulate
function mk_topo {
    echo "@@ Adding links and nodes"
    # Build a minimal UCL network
    # Nodes are created on the fly, and their interface are assigned as
    # <node name>-eth<count>, where count starts at 0 and is increased by 1
    # after each new interface
    add_link Mich SH1C      # Michotte-eth0 <-> SH1C-eth0
    add_link SH1C Hall        # SH1C-eth1     <-> Halles-eth0
    add_link Mich Carn    # Michotte-eth1 <-> Carnoy-eth0
    add_link Hall Pyth # Halles-eth1   <-> Pythagore-eth0
    add_link Carn Pyth   # Carnoy-eth1   <-> Pythagore-eth1
    add_link Carn Stev      # Carnoy-eth2   <-> Stevin-eth0
    add_link Stev Pyth   # Stevin-eth1   <-> Pythagore-eth2

    echo "@@ Adding LANs"
    # You can add your LANs here
    mk_LAN Hall Ha1 Ha2 Ha3 Ha4 #Halles-lan0 host

    mk_LAN Pyth Py1 Py2 Py3 Py4 #Pyth-lan1 hosts
    mk_LAN Pyth Mon # Pyth-lan0-monitoring

    mk_LAN Stev St1 St2 #Stev-lan0 hosts
    mk_LAN Stev DNS2 DHCP2 # Stev-lan1-network-management:secondary DNS, DHCP


    mk_LAN Carn Ca1 Ca2 # Lan0 for student because ran out of time and we could not create VLAN

    mk_LAN Mich Mi1 Mi2 #Mich-lan0 hosts

    mk_LAN SH1C Sh1 Sh2 #SH1C-lan0 hosts
    mk_LAN SH1C DNS DHCP # Halles-lan1-network-management:Primary DNS, DHCP

    echo "@@ Bridging the network"
    # Connect to belneta and belnetb
    bridge_node Pyth eth1 belneta
    bridge_node Hall eth2 belnetb

    echo "@@ Making the virtual network reachable from the host machine"
    # Enable IPv6 forwarding on the bridges
    sysctl -w net.ipv6.conf.breth1.forwarding=1
    sysctl -w net.ipv6.conf.breth2.forwarding=1
    # Add (hopefully) unique source addresses on the bridge
    ip address add dev breth1 "fd00:300::${GROUPNUMBER}:1/64"
    ip address add dev breth2 "fd00:200::${GROUPNUMBER}:1/64"
    # Route the virtual network prefixes over the bridges
    ip route add "fd00:300:${GROUPNUMBER}::/48" via "fd00:300::${GROUPNUMBER}"
    ip route add "fd00:200:${GROUPNUMBER}::/48" via "fd00:200::${GROUPNUMBER}"
}
